version: "3.7"

services:

  db:
    image: honeyball/schema-pg:latest
    environment: 
      POSTGRES_PASSWORD: passwort
    ports:
      - "5432:5432" 

  employee-administration:
    build: ./employee-administration/.
    ports:
      - "8085:8085"
    depends_on: 
      - db  

  project-administration:
    build: ./project-administration/.
    ports:
      - "8086:8086"
    depends_on: 
      - db  

  worktime-administration:
    build: ./worktime-administration/.
    ports:
      - "8087:8087"  
    depends_on: 
      - db

