version: "3.7"

networks:
  backend:
    driver: overlay  

services:  

  zeebe:
    image: camunda/zeebe:0.21.1
    ports:
      - "26500:26500"
      - "9600:9600"  
    deploy:
      restart_policy:
        condition: any          
    networks: 
      - backend  

  db:
    image: honeyball/schema-pg:latest
    environment: 
      POSTGRES_PASSWORD: passwort
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: any  
    networks: 
      - backend  

  employee-administration:
    image: honeyball/zeebe-employee:latest
    ports:
      - "8085:8085"
    environment: 
      - "ZEEBE_URL=zeebe:26500"
    depends_on: 
      - db  
      - zeebe
    deploy:
      restart_policy:
        condition: any  
    networks: 
      - backend    

  project-administration:
    image: honeyball/zeebe-project:latest
    ports:
      - "8086:8086"
    environment: 
      - "ZEEBE_URL=zeebe:26500"  
    depends_on: 
      - db  
      - zeebe
    deploy:
      restart_policy:
        condition: any  
    networks: 
      - backend  

  worktime-administration:
    image: honeyball/zeebe-worktime:latest
    ports:
      - "8087:8087" 
    environment: 
      - "ZEEBE_URL=zeebe:26500"   
    depends_on: 
      - db   
      - zeebe
    deploy:   
      replicas: 2
      restart_policy:
        condition: any
    networks: 
      - backend  
      
