spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console

server:
  port: 8087
