spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true

server:
  port: 8086
